#!/bin/bash

export SYMAS_PREFIX=/opt/symas

export PATH=$PATH:$SYMAS_PREFIX/lib:$SYMAS_PREFIX/bin:$SYMAS_PREFIX/sbin

export SYMAS_ETC=$SYMAS_PREFIX/etc/openldap/etc
export SLAPD_D=$SYMAS_PREFIX/etc/openldap/slapd.d
mkdir $SLAPD_D

slaptest -f ./slapd.conf -F $CONF_D

useradd -u 389 -r ldap

chgrp -R ldap $SYMAS_ETC

cat symas-openldap > /etc/default/symas-openldap

